### ISSUE TITLE
cannot load library libRaptorQ.so on Mac Sierra

### ISSUE THREAD

**Issue by siavashk** [mk-fg/python-libraptorq#2]
On my Mac Sierra (10.12.5), I cannot import libraptorq.

It fails with `OSError: cannot load library libRaptorQ.so: dlopen(libRaptorQ.so, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libRaptorQ.so’`.

I managed to fix it by renaming `libRaptorQ.so` to `libRaptorQ.dylib` on this line:
https://github.com/mk-fg/python-libraptorq/blob/master/libraptorq/__init__.py#L126 

Ideally, importing the shared object should be handled in a platform agnostic manner.

**Comment by mk-fg** [comment]
Yeah, .so is a linux thing, and guess it's .dynlib on OSX (and .dll on Windows).
cffi probably has a wrapper to pick one depending on platform, which should probably be used here.
I've only ran the thing on linux myself, which is why it has that hardcoded .so in there.

Thanks for testing with OSX and providing a solution, should be easy to address, will probably get to it soon.

**Comment by mk-fg** [comment]
Apparently `ffi.dlopen('RaptorQ')` will work fine as well, as it indeed falls back to ctypes.util.find_library, as indicated in that error.
CFFI docs discourage relying on that though, so added explicit call to that ctypes helper, should probably work now.
