### ISSUE TITLE
8e-09 in symbol output

### ISSUE THREAD

**Issue by SethRobertson** [mk-fg/python-libraptorq#6]
I did a `pip install libRaptorQ` and then installed libRaptorQ.so version 0.10.0 from source (as you appear to know, 1.0 beta doesn't work).  I then ran a test:

```
echo "Hello World" > /tmp/x
rq encode -m 1000000 -s 12 -n 3 /tmp/x /tmp/x1

```

The last base64 encoded vector in /tmp/x1 was:

```
    [
      50331648,
      "UjZ7ewtizgs8e-09"
    ]

```

Needless to say "8e-09" is not valid base64.  Smells like a floating point rounding issue, but it is less clear how this could appear in the base64 output.

**Comment by mk-fg** [comment]
Ah yes, I think I've used urlsafe_base64 there, same as most other of my projects:
https://github.com/mk-fg/python-libraptorq/blob/master/libraptorq/__main__.py#L33-L36

So it should be fine, though note the warnings about RFC parameters in the README, which are probably an issue if there's an actual decoding error.

**Comment by mk-fg** [comment]
Thinking about why you were looking at that output a bit, guess you were trying to decode it and use in some other app?

Which I'd advise against - output of that command-line script is not some kind of API, and whole thing is there just as an example and for easy parameter testing from command line, it's probably awful in many ways otherwise (e.g. json for megs of data will take ages!).
Maybe use the module or copy the script code into your tool, so you won't depend on it staying same in this repo, but idk why'd I ever bother changing it either tbh :)
